### PR TITLE
Fixed typo in repo init step

### PR DESCRIPTION
**Pull request by warraagal**
There is no group named "non-default" in the manifests. It is actually "notdefault".

### CODE REVIEW

**Comment by vchong** [comment]
Thanks! Do you want to add an Sob tag?

**Comment by warraagal** [comment]
Please forgive my ignorance. What is an "Sob tag" ?

**Comment by vchong** [comment]
At the bottom of your commit message, add a line that says

`Signed-off-by: Rounak Agarwal <your@email.address>`

You can do this automatically using `git commit -s`. For more info, see https://github.com/OP-TEE/optee_os/blob/master/documentation/github.md#contributing-1.

**Comment by warraagal** [comment]
@vchong I force updated my commit to include an Sob tag. Is it ok now ?

**Comment by vchong** [comment]
Thanks! Note that you can now build using scripts at https://github.com/linaro-swg/optee_android_manifest/tree/lcr-ref-hikey.

**Pull request merged**
